### ISSUE TITLE
Does not compile with OCaml 4.08.0

### ISSUE THREAD

**Issue by toots** [janestreet/base#66]
Error log:
```
#=== ERROR while compiling base.v0.11.1 =======================================#
# context     2.0.0 | macos/x86_64 | ocaml-variants.4.08.0 | pinned(git+file:///Users/toots/sources/ocaml/base#master#c8f6acfc)
# path        ~/.opam/4.08.0/.opam-switch/build/base.v0.11.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p base -j 4
# exit-code   1
# env-file    ~/.opam/log/base-43030-d0f245.env
# output-file ~/.opam/log/base-43030-d0f245.out
### output ###
# [...]
# File "src/or_error.ml", line 15, characters 13-31:
# 15 |   fun arg -> Result.hash_fold_t _hash_fold_a Error.hash_fold_t hsv arg
#                   ^^^^^^^^^^^^^^^^^^
# Alert deprecated: module Base__.Import.Result
# [2016-09] this element comes from the stdlib distributed with OCaml.
# Referring to the stdlib directly is discouraged by Base. You should either
# use the equivalent functionality offered by Base, or if you really want to
# refer to the stdlib, use Caml.Result instead
# File "src/or_error.ml", line 15, characters 13-31:
# 15 |   fun arg -> Result.hash_fold_t _hash_fold_a Error.hash_fold_t hsv arg
#                   ^^^^^^^^^^^^^^^^^^
# Error: Unbound value Result.hash_fold_t
```

**Comment by hhugo** [comment]
Base v0.12.2 has been released. It adds support for ocaml 4.08
ocaml/opam-repository#14177
