### PR TITLE
[v0.14] Add support for OCaml 5.00

### LINKED ISSUE #126: OCaml 5.00 support
```
#=== ERROR while compiling base.v0.14.3 =======================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-variants.5.00.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.00/.opam-switch/build/base.v0.14.3
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p base -j 31
# exit-code            1
# env-file             ~/.opam/log/base-10-c4bd6d.env
# output-file          ~/.opam/log/base-10-c4bd6d.out
### output ###
#       ocamlc shadow-stdlib/gen/.gen.eobjs/byte/mapper.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/5.00/bin/ocamlc.opt -w -40 -g -bin-annot -I shadow-stdlib/gen/.gen.eobjs/byte -I /home/opam/.opam/5.00/lib/ocaml/compiler-libs -I compiler-stdlib/src/.caml.objs/byte -no-alias-deps -o shadow-stdlib/gen/.gen.eobjs/byte/mapper.cmo -c -impl shadow-stdlib/gen/mapper.ml)
# File "shadow-stdlib/gen/mapper.mll", line 7, characters 27-44:
# Error: Unbound value String.capitalize

-       ocamlc shadow-stdlib/gen/.gen.eobjs/byte/mapper.{cmi,cmo,cmt} (exit 2)
- (cd _build/default && /home/opam/.opam/5.00/bin/ocamlc.opt -w -40 -g -bin-annot -I shadow-stdlib/gen/.gen.eobjs/byte -I /home/opam/.opam/5.00/lib/ocaml/compiler-libs -I compiler-stdlib/src/.caml.objs/byte -no-alias-deps -o shadow-stdlib/gen/.gen.eobjs/byte/mapper.cmo -c -impl shadow-stdlib/gen/mapper.ml)
- File "shadow-stdlib/gen/mapper.mll", line 7, characters 27-44:
- Error: Unbound value String.capitalize
```

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes #126

### CODE REVIEW

**Comment by bcc32** [comment]
Thanks for the fix, Kate!  I've pulled it in and made a couple changes to make sure it builds internally.  I tried the naive thing to make sure it still compiles with 5.00, but I got an error:

```
$ opam switch create 5.00 ocaml-base-compiler.5.00
[ERROR] No compiler matching 'ocaml-base-compiler.5.00' found, use 'opam switch list-available' to see what is available, or use '--packages' to select packages explicitly.
```

Am I missing something obvious (I did remember to `opam update` this time :smile:)?  Alternatively, would you prefer for me to just edit this PR and you can test it on your end?

**Comment by Sudha247** [comment]
@bcc32 you can install the compiler with:

```
opam switch create 5.00.0+trunk
```

**Comment by Sudha247** [comment]
@kit-ty-kate any idea why I'm getting this error on trunk (is it missing some patched dependency?)

```
src/.base.objs/byte/base__Import.cmo [...]
# File "src/import.ml", line 3, characters 8-40:
# 3 | include Sexp.Private.Raw_grammar.Builtin
#             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Sexp.Private.Raw_grammar
```

**Comment by kit-ty-kate** [comment]
@Sudha247 are you sure you’re not using base’s master branch instead? Everything is already in https://github.com/kit-ty-kate/opam-alpha-repository so you shouldn’t have to compile branches manually

**Comment by bcc32** [comment]
Thanks both.  I needed to add @kit-ty-kate's opam repo and then use the correct compiler name that @Sudha247 gave.  I made some changes that build with 5.00 on my end but if you would like to check the compile on your end again, please do.

**Comment by aalekseyev** [comment]
I hate being the DCO police, but I won't be able to release this code publicly unless the patch is properly signed off.
@kit-ty-kate, can you sign off your commits? (I'm assuming you know what that is about)

File: src/import0.ml [hunk 1]
```diff
@@ -45,6 +45,8 @@ type 'a ref = 'a Caml.ref = { mutable contents : 'a }
 (* Reshuffle [Caml] so that we choose the modules using labels when available. *)
 module Caml = struct
 
+  include Caml
+
```
Comment (kit-ty-kate) [inline src/import0.ml:49]: The reason I’ve not signed the DCO or removed the draft state of this PR is that I was under the impression this part wouldn’t go in.

Also please do whatever you want with the code, it isn’t mine to begin with and this PR is only here to serve as the hotfix corresponding PR for opam-alpha-repository as far as I’m concerned.

Comment (aalekseyev) [reply src/import0.ml:49]: > it isn’t mine to begin with

Well, that only makes things worse because then we'd need signoff of the original author, or something equivalent.
Taking a quick look at the diff, I see it's mostly deletions, so hardly copyrightable, so maybe it's fine.

Anyway, @bcc32, IANAL, but it's my responsibility to make you aware that the issue exists.

Comment (bcc32) [reply src/import0.ml:49]: FYI, I went through and reimplemented some of these fixes from scratch internally, some of them slightly differently.  There's an issue with the Ephemeron API which means we can't be compatible with both 4.12 and 5.00 at the same time, so I haven't made any changes there yet.  @kit-ty-kate, should I close this PR seeing as your branch would still exist, or would you like to keep it open?

**Comment by kit-ty-kate** [comment]
@bcc32 any news on that?
